FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# Copy script
COPY mongo_to_loki.py .

# Run the script
CMD ["python", "mongo_to_loki.py"]